[package]
name = "rustoguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chargrid_graphical = "0.7"
chargrid = "0.4"
